/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include<stdio.h>
#include<stdlib.h>
#include<string.h>
#include "twitter.h"


int *
create_user(char **argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert client code here
	 */

	return &result;
}

char **
list_users(void *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert client code here
	 */

	return &result;
}

int *
follow(followUser *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert client code here
	 */

	return &result;
}

int *
post_topic(post *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert client code here
	 */

	return &result;
}

char **
hashtags(void *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert client code here
	 */

	return &result;
}

int *
new_topic(topic *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert client code here
	 */

	return &result;
}

int *
unfollow(followUser *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert client code here
	 */

	return &result;
}

int *
retrievetopic(retrieve *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert client code here
	 */

	return &result;
}

int *
twitte(twitteMessage *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert client code here
	 */

	return &result;
}

void readAllFile(FILE *f){
	char    *buffer;
	long    numbytes;

	fseek(f, 0L, SEEK_END);
	numbytes = ftell(f);
	
	fseek(f, 0L, SEEK_SET);	

	buffer = (char*)calloc(numbytes, sizeof(char));	
	
	if(buffer == NULL)
		exit(1);
	
	fread(buffer, sizeof(char), numbytes, f);
	
	printf("%s\n", buffer);
	
	free(buffer);
}
void verifyParams(int argc, char *argv[]){
	
	FILE *file = NULL;

	if(strcmp(argv[1], "-h") == 0 || strcmp(argv[1], "-help") == 0){
		file = fopen("instructions.txt", "r");
		if(file != NULL){
			printf("Error! opening file");
       		exit(1);
		}

		readAllFile(file);

		fclose(file);
		exit (1);
	}


	if (argc!=4){
			fprintf (stderr,"Usage: %s hostname [function_name]\n",argv[0]);
			exit (1);
	}
}


int
main (int argc, char *argv[])
{
	CLIENT *clnt;
	int x,y;

	verifyParams(argc, argv);


	return (0);
}
