/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "twitter.h"
// #include "MysqlConnector.h"


int *
create_user_1_svc(char **argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

char **
list_users_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
follow_1_svc(data *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
post_topic_1_svc(data *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

char **
hashtags_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
new_topic_1_svc(data *argp, struct svc_req *rqstp)
{
	static int  result = 0;

	printf("Passei Aqui1\n");
	printf("%s", argp->(username));
	printf("Passei Aqui2\n");
	

	return &result;
}

int *
unfollow_1_svc(data *argp, struct svc_req *rqstp)
{
	static int  result;


	return &result;
}

char **
retrievetopic_1_svc(data *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
twitte_1_svc(data *argp, struct svc_req *rqstp)
{
	static int  result;


	return &result;
}
