/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "twitter.h"

bool_t
xdr_data (XDR *xdrs, data *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->username, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->otherName, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->text, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->topic, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->timestamp, ~0))
		 return FALSE;
	return TRUE;
}
