/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "twitter.h"


void
interface_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	char * create_user_1_arg;
	char * *result_2;
	char *list_users_1_arg;
	int  *result_3;
	followUser  follow_1_arg;
	int  *result_4;
	post  post_topic_1_arg;
	char * *result_5;
	char *hashtags_1_arg;
	int  *result_6;
	topic  new_topic_1_arg;
	int  *result_7;
	followUser  unfollow_1_arg;
	int  *result_8;
	retrieve  retrievetopic_1_arg;
	int  *result_9;
	twitteMessage  twitte_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, INTERFACE_PROG, INTERFACE_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = create_user_1(&create_user_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = list_users_1((void*)&list_users_1_arg, clnt);
	if (result_2 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = follow_1(&follow_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = post_topic_1(&post_topic_1_arg, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = hashtags_1((void*)&hashtags_1_arg, clnt);
	if (result_5 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = new_topic_1(&new_topic_1_arg, clnt);
	if (result_6 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_7 = unfollow_1(&unfollow_1_arg, clnt);
	if (result_7 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_8 = retrievetopic_1(&retrievetopic_1_arg, clnt);
	if (result_8 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_9 = twitte_1(&twitte_1_arg, clnt);
	if (result_9 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	interface_prog_1 (host);
exit (0);
}
