/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "twitter.h"
// #include "MysqlConnector.h"

#define host "localhost"
#define user "root"
#define password ""
#define dbName "twitter"

int *
create_user_1_svc(char **argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

char **
list_users_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
follow_1_svc(followUser *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
post_topic_1_svc(post *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

char **
hashtags_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
new_topic_1_svc(topic *argp, struct svc_req *rqstp)
{
	static int  result;
	// MYSQL *con = mysqlConnector(host, user, password, dbName);
	char *query1 = NULL, *query2 = NULL, *query3 = NULL, *query4 = NULL;

    // if (con == NULL) 
    // {
    //     exit(1);
    // }
	query1 = strcat("INSERT INTO topic (topic, id_user) VALUES(", argp->topic);
	query2 = strcat(query1, ", ");
	query3 = strcat(query2, argp->username);
	query4 = strcat(query3, ");");

	// result = insertDate(con, query4);
	printf("%s", query4);
	free(query1);
	free(query2);
	free(query3);
	free(query4);

	return &result;
}

int *
unfollow_1_svc(followUser *argp, struct svc_req *rqstp)
{
	static int  result;
	// MYSQL *con = mysqlConnector(host, user, password, dbName);
	char *query1 = NULL, *query2 = NULL, *query3 = NULL, *query4 = NULL;

    // if (con == NULL) 
    // {
    //     exit(1);
    // }
	query1 = strcat("DELETE FROM followers WHERE id_user='", argp->username);
	query2 = strcat(query1, "'AND WHERE id_follower='");
	query3 = strcat(query2, argp->otherName);
	query4 = strcat(query3, "');");

	// result = deleteDate(con, query4);
	printf("%s", query4);

	free(query1);
	free(query2);
	free(query3);
	free(query4);

	return &result;
}

char **
retrievetopic_1_svc(retrieve *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
twitte_1_svc(twitteMessage *argp, struct svc_req *rqstp)
{
	static int  result;
	// MYSQL *con = mysqlConnector(host, user, password, dbName);
	char *query1 = NULL, *query2 = NULL, *query3 = NULL, *query4 = NULL, *timestamp = NULL;

    // if (con == NULL) 
    // {
    //     exit(1);
    // }
	query1 = strcat("INSET INTO twitte (id, id_user, text, twitte_time, topic) VALUES(null, '", argp->username);
	query2 = strcat(query1, "', '");
	query3 = strcat(query2, argp->text);
	query4 = strcat(query3, "', '");
	free(query1);
	free(query2);
	free(query3);
	query1 = strcat(query4, timestamp);
	query2 = strcat(query1, "', '");
	query3 = strcat(query2, argp->topic);
	free(query4);
	query4 = strcat(query3, "');");


	// result = insertDate(con, query4);
	printf("%s", query4);
	
	free(query1);
	free(query2);
	free(query3);
	free(query4);

	return &result;
}
