/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TWITTER_H_RPCGEN
#define _TWITTER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct data {
	char *username;
	char *otherName;
	char *text;
	char *topic;
	char *timestamp;
};
typedef struct data data;

#define TWITTER_PROG 0x30D0D0DF
#define TWITTER_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define create_user 1
extern  int * create_user_1(char **, CLIENT *);
extern  int * create_user_1_svc(char **, struct svc_req *);
#define list_users 2
extern  char ** list_users_1(void *, CLIENT *);
extern  char ** list_users_1_svc(void *, struct svc_req *);
#define follow 3
extern  int * follow_1(data *, CLIENT *);
extern  int * follow_1_svc(data *, struct svc_req *);
#define post_topic 4
extern  int * post_topic_1(data *, CLIENT *);
extern  int * post_topic_1_svc(data *, struct svc_req *);
#define hashtags 5
extern  char ** hashtags_1(void *, CLIENT *);
extern  char ** hashtags_1_svc(void *, struct svc_req *);
#define new_topic 6
extern  int * new_topic_1(data *, CLIENT *);
extern  int * new_topic_1_svc(data *, struct svc_req *);
#define unfollow 7
extern  int * unfollow_1(data *, CLIENT *);
extern  int * unfollow_1_svc(data *, struct svc_req *);
#define retrievetopic 8
extern  char ** retrievetopic_1(data *, CLIENT *);
extern  char ** retrievetopic_1_svc(data *, struct svc_req *);
#define twitte 9
extern  int * twitte_1(data *, CLIENT *);
extern  int * twitte_1_svc(data *, struct svc_req *);
extern int twitter_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define create_user 1
extern  int * create_user_1();
extern  int * create_user_1_svc();
#define list_users 2
extern  char ** list_users_1();
extern  char ** list_users_1_svc();
#define follow 3
extern  int * follow_1();
extern  int * follow_1_svc();
#define post_topic 4
extern  int * post_topic_1();
extern  int * post_topic_1_svc();
#define hashtags 5
extern  char ** hashtags_1();
extern  char ** hashtags_1_svc();
#define new_topic 6
extern  int * new_topic_1();
extern  int * new_topic_1_svc();
#define unfollow 7
extern  int * unfollow_1();
extern  int * unfollow_1_svc();
#define retrievetopic 8
extern  char ** retrievetopic_1();
extern  char ** retrievetopic_1_svc();
#define twitte 9
extern  int * twitte_1();
extern  int * twitte_1_svc();
extern int twitter_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_data (XDR *, data*);

#else /* K&R C */
extern bool_t xdr_data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TWITTER_H_RPCGEN */
