/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include<stdio.h>
#include<stdlib.h>
#include<string.h>
#include "twitter.h"

#define fileHelpName "instructions.txt"

void readAllFile(char *fileName){
	char    *buffer;
	long    numbytes;
	FILE *f = NULL;

	f = fopen(fileName, "r");
	if(f == NULL){
		printf("Error! opening file");
		exit(1);
	}

	fseek(f, 0L, SEEK_END);
	numbytes = ftell(f);
	
	fseek(f, 0L, SEEK_SET);	

	buffer = (char*)calloc(numbytes, sizeof(char));	
	
	if(buffer == NULL)
		exit(1);
	
	fread(buffer, sizeof(char), numbytes, f);
	
	printf("%s\n", buffer);
	
	free(buffer);
}


void verifyParams(int argc, char **argv){
	
	FILE *file = NULL;

	if(strcmp(argv[1], "-h") == 0 || strcmp(argv[1], "-help") == 0){

		readAllFile(fileHelpName);

		exit (1);
	}

	if (argc!=4){
			fprintf (stderr,"Usage: %s hostname [function_name] [params1, ..., paramsn]\n",argv[0]);
			exit (1);
	}
}


int
main (int argc, char *argv[])
{
	CLIENT *clnt;
	int x,y;

	verifyParams(argc, argv);


	return (0);
}
