/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TWITTER_H_RPCGEN
#define _TWITTER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct followUser {
	char *username;
	char *otherName;
};
typedef struct followUser followUser;

struct post {
	char *username;
	char *topic;
	char *text;
};
typedef struct post post;

struct topic {
	char *username;
	char *topic;
};
typedef struct topic topic;

struct retrieve {
	char *username;
	char *topic;
	char *timestamp;
};
typedef struct retrieve retrieve;

struct twitteMessage {
	char *username;
	char *text;
};
typedef struct twitteMessage twitteMessage;

#define INTERFACE_PROG 12345678
#define INTERFACE_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define create_user 1
extern  int * create_user_1(char **, CLIENT *);
extern  int * create_user_1_svc(char **, struct svc_req *);
#define list_users 2
extern  data * list_users_1(void *, CLIENT *);
extern  data * list_users_1_svc(void *, struct svc_req *);
#define follow 3
extern  int * follow_1(followUser *, CLIENT *);
extern  int * follow_1_svc(followUser *, struct svc_req *);
#define post_topic 4
extern  int * post_topic_1(post *, CLIENT *);
extern  int * post_topic_1_svc(post *, struct svc_req *);
#define hashtags 5
extern  char ** hashtags_1(void *, CLIENT *);
extern  char ** hashtags_1_svc(void *, struct svc_req *);
#define new_topic 6
extern  int * new_topic_1(topic *, CLIENT *);
extern  int * new_topic_1_svc(topic *, struct svc_req *);
#define unfollow 7
extern  int * unfollow_1(followUser *, CLIENT *);
extern  int * unfollow_1_svc(followUser *, struct svc_req *);
#define retrievetopic 8
extern  int * retrievetopic_1(retrieve *, CLIENT *);
extern  int * retrievetopic_1_svc(retrieve *, struct svc_req *);
#define twitte 9
extern  int * twitte_1(twitteMessage *, CLIENT *);
extern  int * twitte_1_svc(twitteMessage *, struct svc_req *);
extern int interface_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define create_user 1
extern  int * create_user_1();
extern  int * create_user_1_svc();
#define list_users 2
extern  data * list_users_1();
extern  data * list_users_1_svc();
#define follow 3
extern  int * follow_1();
extern  int * follow_1_svc();
#define post_topic 4
extern  int * post_topic_1();
extern  int * post_topic_1_svc();
#define hashtags 5
extern  char ** hashtags_1();
extern  char ** hashtags_1_svc();
#define new_topic 6
extern  int * new_topic_1();
extern  int * new_topic_1_svc();
#define unfollow 7
extern  int * unfollow_1();
extern  int * unfollow_1_svc();
#define retrievetopic 8
extern  int * retrievetopic_1();
extern  int * retrievetopic_1_svc();
#define twitte 9
extern  int * twitte_1();
extern  int * twitte_1_svc();
extern int interface_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_followUser (XDR *, followUser*);
extern  bool_t xdr_post (XDR *, post*);
extern  bool_t xdr_topic (XDR *, topic*);
extern  bool_t xdr_retrieve (XDR *, retrieve*);
extern  bool_t xdr_twitteMessage (XDR *, twitteMessage*);

#else /* K&R C */
extern bool_t xdr_followUser ();
extern bool_t xdr_post ();
extern bool_t xdr_topic ();
extern bool_t xdr_retrieve ();
extern bool_t xdr_twitteMessage ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TWITTER_H_RPCGEN */
